### ISSUE TITLE
Enhance the config schema

### ISSUE THREAD

**Issue by warrenvw** [StackStorm-Exchange/stackstorm-elasticsearch#12]
Enhance the config schema to support multiple environments. Each environment contains a set of configuration parameters.

```
elasticsearch:
  dev:
    host: elk-dev
    port: 9222
  production:
    host: elk-prod
    port: 9200
```
